package com.groupironmencompanion.map;

import com.google.gson.Gson;
import com.google.gson.JsonSyntaxException;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.HashMap;
import java.util.Map;
import javax.annotation.Nullable;
import lombok.extern.slf4j.Slf4j;
import net.runelite.api.coords.WorldPoint;

/**
 * Works out which named area of the world a position is in, and which surface entrance leads
 * there, from data extracted out of the game cache.
 * <p>
 * The world map draws each detached area, dungeons included, in its own corner of the world
 * grid, and RuneLite only draws a world map point when the map currently on screen actually
 * covers it. So a member standing in a dungeon appears correctly once you pan to that
 * dungeon's map, and is simply absent from the overworld. This class supplies the missing
 * half: where on the overworld to draw a marker saying "they are below here".
 * <p>
 * The backing resource is generated by {@code tools/mapdump}, which reads the world map
 * definitions and the map's own intermap links straight out of the game cache. Nothing here
 * is hand-measured, and regenerating it after a game update is a single command.
 */
@Slf4j
public final class MapAreas
{
	private static final String RESOURCE = "/com/groupironmencompanion/map-areas.json";

	/**
	 * The standard underground band. Areas at or above this are laid out directly beneath
	 * their surface counterpart, offset by exactly this much, which is what makes the
	 * projection fallback below work when the cache offers no explicit link.
	 */
	private static final int UNDERGROUND_Y = 6400;

	/** How near a link outside every known area has to be before it is trusted, in tiles. */
	private static final int LOOSE_LINK_RADIUS = 64;

	private static volatile MapAreas instance;

	private final Map<Integer, Area> bySquare;
	private final Link[] looseLinks;

	private MapAreas(Resource resource)
	{
		bySquare = new HashMap<>();
		if (resource.areas != null)
		{
			for (Area area : resource.areas)
			{
				if (area.squares == null)
				{
					continue;
				}
				for (int square : area.squares)
				{
					bySquare.put(square, area);
				}
			}
		}
		looseLinks = resource.looseLinks == null ? new Link[0] : resource.looseLinks;
	}

	public static MapAreas get(Gson gson)
	{
		MapAreas local = instance;
		if (local == null)
		{
			synchronized (MapAreas.class)
			{
				local = instance;
				if (local == null)
				{
					instance = local = load(gson);
				}
			}
		}
		return local;
	}

	private static MapAreas load(Gson gson)
	{
		try (InputStream in = MapAreas.class.getResourceAsStream(RESOURCE))
		{
			if (in == null)
			{
				log.warn("Group Ironmen Tracker In-Game Companion: {} is missing from the plugin jar", RESOURCE);
				return new MapAreas(new Resource());
			}
			Resource resource = gson.fromJson(
				new InputStreamReader(in, StandardCharsets.UTF_8), Resource.class);
			return new MapAreas(resource == null ? new Resource() : resource);
		}
		catch (IOException | JsonSyntaxException e)
		{
			log.warn("Group Ironmen Tracker In-Game Companion: could not read {}", RESOURCE, e);
			return new MapAreas(new Resource());
		}
	}

	/** Squares are 64x64 tiles, packed the same way the generator packs them. */
	private static int squareOf(int x, int y)
	{
		return (x / 64) * 256 + (y / 64);
	}

	/**
	 * Describes where a position is. Returns null when the position is on the overworld map,
	 * because a member standing there is already drawn where they are.
	 */
	@Nullable
	public Located locate(WorldPoint point)
	{
		if (point == null)
		{
			return null;
		}

		Area area = bySquare.get(squareOf(point.getX(), point.getY()));
		if (area == null && point.getY() < UNDERGROUND_Y)
		{
			// Not in any detached area and not in the underground band: this is the overworld.
			return null;
		}

		String areaName = area == null ? null : area.name;

		// 1. The area's own exits, as the world map itself defines them.
		if (area != null && area.exits != null && area.exits.length > 0)
		{
			Link best = nearest(area.exits, point, Integer.MAX_VALUE);
			if (best != null)
			{
				return new Located(areaName, new WorldPoint(best.ex, best.ey, 0), best.name);
			}
		}

		// 2. A link the cache places outside every named area, if one is genuinely close.
		Link loose = nearest(looseLinks, point, LOOSE_LINK_RADIUS);
		if (loose != null)
		{
			return new Located(areaName, new WorldPoint(loose.ex, loose.ey, 0), loose.name);
		}

		// 3. Project straight up out of the underground band. Accurate to a few tiles,
		// because these areas are built directly below where they connect to.
		if (point.getY() >= UNDERGROUND_Y)
		{
			return new Located(areaName,
				new WorldPoint(point.getX(), point.getY() - UNDERGROUND_Y, 0), null);
		}

		// Known area, no way to place it on the surface. The name alone is still worth having.
		return new Located(areaName, null, null);
	}

	@Nullable
	private static Link nearest(Link[] links, WorldPoint point, int maxDistance)
	{
		Link best = null;
		long bestDistance = Long.MAX_VALUE;
		long limit = (long) maxDistance * maxDistance;

		for (Link link : links)
		{
			long dx = link.x - point.getX();
			long dy = link.y - point.getY();
			long distance = dx * dx + dy * dy;
			if (distance < bestDistance)
			{
				bestDistance = distance;
				best = link;
			}
		}

		return bestDistance <= limit ? best : null;
	}

	/** Where a member is, and how to find them from the overworld. */
	public static final class Located
	{
		private final String areaName;
		private final WorldPoint entrance;
		private final String entranceName;

		Located(String areaName, WorldPoint entrance, String entranceName)
		{
			this.areaName = areaName;
			this.entrance = entrance;
			this.entranceName = entranceName;
		}

		/** The game's name for the map they are on, e.g. "Taverley Underground". */
		@Nullable
		public String getAreaName()
		{
			return areaName;
		}

		/** The surface point that leads to them, or null when nothing leads there. */
		@Nullable
		public WorldPoint getEntrance()
		{
			return entrance;
		}

		/** The entrance's own name, e.g. "Taverley Dungeon", when one is known. */
		@Nullable
		public String getEntranceName()
		{
			return entranceName == null || entranceName.isEmpty() ? null : entranceName;
		}

		/** The best label available for this location. */
		public String describe()
		{
			if (getEntranceName() != null)
			{
				return entranceName;
			}
			if (areaName != null)
			{
				return areaName;
			}
			return "underground";
		}
	}

	// ------------------------------------------------------------------
	// Resource shape, bound by Gson from concrete classes and plain arrays
	// ------------------------------------------------------------------

	private static final class Resource
	{
		private Area[] areas;
		private Link[] looseLinks;
	}

	private static final class Area
	{
		private String name;
		private int[] squares;
		private Link[] exits;
	}

	private static final class Link
	{
		private int x;
		private int y;
		private int ex;
		private int ey;
		private String name;
	}
}
